'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  DEFAULT_RPC_URL,
  explorerTransactionUrl,
  inputFailure,
  parseEvidenceJson,
  verifyEvidenceInBrowser,
  type MirroredEvidenceEntry,
  type MirroredEvidenceIndex,
  type PanelResult,
  type PanelStep,
} from './verify-chain-browser';
import { formatLeadSeconds } from '../../scripts/lib/anchor-lead.js';
import './verify-panel.css';

const PASTED = '__pasted__';

function short(value: string, start = 10, end = 8) { return `${value.slice(0, start)}…${value.slice(-end)}`; }

function interval(sec: number) {
  if (sec % 86400 === 0) return `${sec / 86400}D`;
  if (sec % 3600 === 0) return `${sec / 3600}H`;
  return `${Math.round(sec / 60)}M`;
}

function label(entry: MirroredEvidenceEntry) {
  const observed = new Date(Number(BigInt(entry.observed_at_ns) / 1_000_000n)).toISOString().slice(0, 16).replace('T', ' ');
  return `${entry.symbol} / ${interval(entry.interval_sec)} · ${short(entry.market_id, 6, 4)} · ${observed}Z · ${entry.outcome}${entry.flagship ? ' · README example' : ''}`;
}

function Verdict({ verdict }: { verdict: PanelResult['verdict'] }) {
  const tone = verdict === 'PASS' ? 'pass' : verdict === 'FAIL' ? 'fail' : 'unprovable';
  return <em className={`vp-verdict ${tone}`}>{verdict}</em>;
}

/**
 * The lead-time annotation the CLI prints beside step 5. Deliberately outside
 * the numbered list and visually unlike a verdict chip: step 5 already decided
 * PASS or NOT PROVABLE, and this measures the margin it left unstated.
 */
function AnchorLead({ lead }: { lead: NonNullable<PanelResult['anchorLead']> }) {
  return (
    <div className={`vp-lead ${lead.low ? 'low' : ''}`}>
      <p className="vp-lead-measure">
        <span>ANCHOR LEAD</span>
        <b>{lead.lead_sec === null ? 'UNAVAILABLE' : formatLeadSeconds(lead.lead_sec)}</b>
        <code>{lead.line}</code>
      </p>
      {lead.warning !== null && (
        <p className="vp-lead-warning">
          <em>WARNING · LOW_LEAD</em>
          <small>
            The root was mined only {formatLeadSeconds(lead.lead_sec ?? 0)} before this market
            expired, under the {lead.threshold_sec}-second floor. This is a warning about how
            little was still unknown, not a verdict: the verdict above is unchanged, and the
            threshold is never applied retroactively to a published record.
          </small>
        </p>
      )}
    </div>
  );
}

/** Five rows in the CLI's own order, each with its printed line and one line of prose. */
function StepRow({ step }: { step: PanelStep }) {
  const tone = step.status === 'PASS'
    ? 'pass'
    : step.status === 'FAIL' ? 'fail' : step.status === 'NOT PROVABLE' ? 'unprovable' : 'idle';
  return (
    <li className={`vp-step ${tone}`}>
      <span className="vp-step-status">{step.status}</span>
      <div>
        <code>{step.line}</code>
        <small>{step.explanation}</small>
      </div>
    </li>
  );
}

export default function VerifyPanel() {
  const [index, setIndex] = useState<MirroredEvidenceIndex | null>(null);
  const [indexError, setIndexError] = useState<string | null>(null);
  const [choice, setChoice] = useState('');
  const [pasted, setPasted] = useState('');
  const [rpcUrl, setRpcUrl] = useState('');
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState<PanelResult | null>(null);
  const [elapsedMs, setElapsedMs] = useState<number | null>(null);

  useEffect(() => {
    let live = true;
    fetch('/evidence/index.json')
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return response.json() as Promise<MirroredEvidenceIndex>;
      })
      .then((value) => {
        if (!live) return;
        setIndex(value);
        setChoice(value.entries.find((entry) => entry.flagship)?.file ?? value.entries[0]?.file ?? '');
      })
      .catch((error: unknown) => {
        if (!live) return;
        // The mirror is generated by scripts/publish-evidence.ts; a build made
        // without it still has to offer the paste path rather than look broken.
        setIndexError(error instanceof Error ? error.message : String(error));
        setChoice(PASTED);
      });
    return () => { live = false; };
  }, []);

  const selected = useMemo(
    () => index?.entries.find((entry) => entry.file === choice) ?? null,
    [index, choice],
  );

  const run = useCallback(async () => {
    setRunning(true);
    setResult(null);
    const started = Date.now();
    try {
      let text: string;
      if (choice === PASTED) {
        if (pasted.trim() === '') {
          setResult(inputFailure('paste an evidence JSON file first'));
          return;
        }
        text = pasted;
      } else {
        const response = await fetch(`/evidence/${choice}`);
        if (!response.ok) throw new Error(`could not load /evidence/${choice}: HTTP ${response.status}`);
        text = await response.text();
      }
      setResult(await verifyEvidenceInBrowser(parseEvidenceJson(text), { rpcUrl }));
    } catch (error) {
      setResult(inputFailure(error instanceof Error ? error.message : String(error)));
    } finally {
      setElapsedMs(Date.now() - started);
      setRunning(false);
    }
  }, [choice, pasted, rpcUrl]);

  const anchorTx = result?.anchorTx ?? selected?.anchor_tx ?? null;

  return (
    <div className="vp" aria-label="Browser verification of one sealed forecast">
      <div className="vp-head">
        <span>ENCLOSURE B — in-browser verifier · no install</span>
        <button type="button" onClick={() => { void run(); }} disabled={running}>
          {running ? 'VERIFYING…' : 'VERIFY THIS FORECAST'}
        </button>
      </div>

      <p className="vp-lede">
        The five checks below are the ones <code>npm run verify</code> prints. This panel imports the
        same <code>src/evidence-verifier.ts</code> the CLI uses and reads Somnia Shannon directly over
        public JSON-RPC; only the transport differs.
      </p>

      <div className="vp-controls">
        <label>
          <span>FORECAST</span>
          <select value={choice} onChange={(event) => { setChoice(event.target.value); setResult(null); }}>
            {index?.entries.map((entry) => (
              <option key={entry.file} value={entry.file}>{label(entry)}</option>
            ))}
            <option value={PASTED}>Paste your own evidence JSON…</option>
          </select>
        </label>
        <label>
          <span>RPC URL (OPTIONAL)</span>
          <input
            type="text"
            value={rpcUrl}
            placeholder={DEFAULT_RPC_URL}
            spellCheck={false}
            onChange={(event) => setRpcUrl(event.target.value)}
          />
        </label>
      </div>

      {indexError !== null && (
        <p className="vp-note">
          No mirrored evidence on this build ({indexError}). Run <code>npx tsx scripts/publish-evidence.ts</code>{' '}
          before <code>npm run build</code>, or paste a file from <code>evidence/</code> below.
        </p>
      )}

      {choice === PASTED && (
        <label className="vp-paste">
          <span>EVIDENCE JSON</span>
          <textarea
            value={pasted}
            rows={7}
            spellCheck={false}
            placeholder='Paste any file from evidence/ — change one digit of p_agent and watch step 1 fail.'
            onChange={(event) => { setPasted(event.target.value); setResult(null); }}
          />
        </label>
      )}

      {selected !== null && choice !== PASTED && (
        <div className="vp-facts">
          <p><span>MARKET</span><code>{selected.market_id}</code></p>
          <p><span>ROOT</span><code>{selected.root}</code></p>
          <p>
            <span>ANCHOR TX</span>
            <a href={explorerTransactionUrl(selected.anchor_tx)} target="_blank" rel="noreferrer">
              <code>{short(selected.anchor_tx, 12, 10)}</code> ↗
            </a>
          </p>
        </div>
      )}

      {result !== null && (
        <div className="vp-result">
          <div className="vp-result-head">
            <Verdict verdict={result.verdict} />
            <span>
              {result.verdict === 'PASS' && 'Sealed before expiry and unchanged since.'}
              {result.verdict === 'FAIL' && 'The disclosed bytes do not match what was anchored.'}
              {result.verdict === 'NOT PROVABLE' && 'Internally consistent, but the anchor did not precede expiry.'}
            </span>
            {elapsedMs !== null && <b>{(elapsedMs / 1000).toFixed(1)} s</b>}
          </div>
          {result.inputError !== null && <p className="vp-input-error">FAIL input {result.inputError}</p>}
          <ol className="vp-steps">
            {result.steps.map((step) => <StepRow key={step.step} step={step} />)}
          </ol>
          {result.anchorLead !== null && <AnchorLead lead={result.anchorLead} />}
          {anchorTx !== null && (
            <p className="vp-explorer">
              <a href={explorerTransactionUrl(anchorTx)} target="_blank" rel="noreferrer">
                Open anchor transaction {short(anchorTx, 12, 10)} on shannon-explorer ↗
              </a>
            </p>
          )}
        </div>
      )}
    </div>
  );
}
